config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :invoices
  resources :orders
  root 'application#index'
end

app/views/main/_navbar_app.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">AIRY</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <form class="form-inline my-2 my-lg-0">
        <div class="input-group">
          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </div>
        </div>
      </form>
    </div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Cart
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if @cart %>
            <div class="dropdown-item">Hello <%= current_customer.email %></div>
            <div class="dropdown-divider"></div>
            <% @cart.each do |order| %>
              <a class="dropdown-item" href="<%= product_path(order[:product].id) %>">
                (<%= order[:product].brand %>) <%= order[:product].name %> x <%= order[:quantity] %>
              </a>
            <% end %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item mt-5" href="#">
              <button class="btn btn-primary w-100">Check out</button>
            </a>
          <% else %>
            <a class="dropdown-item text-muted">Your cart is empty.</a>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">Hello Guest, you're not <%= link_to 'sign in', customer_session_path %></div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/main/catalogue.html.erb
<%= content_for :title do %>
  Catalogue
<% end %>
<div class="jumbotron">
  <h1 class="text-center">Catalogue</h1>
</div>
<div class="container mt-5">
  <div class="row mt-5">
    <% @products.each do |p| %>
      <%= link_to product_path(p), class: 'card-link' do %>
        <div class="card m-2" style="width: 18rem;">
          <img src="<%= p.img_url || 'http://via.placeholder.com/350x250' %>" alt="product-img" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= p.name %></h5>
            <p class="card-text">
              <span class="text-muted"><%= p.brand %></span><br>
            <h1><%= p.price %> $</h1>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>